package com.cym.struts2.demo1.mapper;

import com.cym.struts2.demo1.bean.WsGovernment;
import com.cym.struts2.demo1.bean.WsGovernmentExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;


public interface WsGovernmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int countByExample(WsGovernmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int deleteByExample(WsGovernmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int insert(WsGovernment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int insertSelective(WsGovernment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    List<WsGovernment> selectByExample(WsGovernmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    WsGovernment selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WsGovernment record, @Param("example") WsGovernmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WsGovernment record, @Param("example") WsGovernmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WsGovernment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WsGovernment record);
}