package com.cym.struts2.demo1.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WsGovernmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public WsGovernmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("REGION_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("REGION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(BigDecimal value) {
            addCriterion("REGION_ID =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(BigDecimal value) {
            addCriterion("REGION_ID <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(BigDecimal value) {
            addCriterion("REGION_ID >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REGION_ID >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(BigDecimal value) {
            addCriterion("REGION_ID <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REGION_ID <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<BigDecimal> values) {
            addCriterion("REGION_ID in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<BigDecimal> values) {
            addCriterion("REGION_ID not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGION_ID between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGION_ID not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("ORG_CODE =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("ORG_CODE <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("ORG_CODE >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CODE >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("ORG_CODE <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("ORG_CODE <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("ORG_CODE like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("ORG_CODE not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("ORG_CODE in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("ORG_CODE not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("ORG_CODE between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("ORG_CODE not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("ORG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("ORG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("ORG_NAME =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("ORG_NAME <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("ORG_NAME >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("ORG_NAME <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("ORG_NAME like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("ORG_NAME not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("ORG_NAME in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("ORG_NAME not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("ORG_NAME between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME not between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andEasyNameIsNull() {
            addCriterion("EASY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEasyNameIsNotNull() {
            addCriterion("EASY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEasyNameEqualTo(String value) {
            addCriterion("EASY_NAME =", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameNotEqualTo(String value) {
            addCriterion("EASY_NAME <>", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameGreaterThan(String value) {
            addCriterion("EASY_NAME >", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameGreaterThanOrEqualTo(String value) {
            addCriterion("EASY_NAME >=", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameLessThan(String value) {
            addCriterion("EASY_NAME <", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameLessThanOrEqualTo(String value) {
            addCriterion("EASY_NAME <=", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameLike(String value) {
            addCriterion("EASY_NAME like", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameNotLike(String value) {
            addCriterion("EASY_NAME not like", value, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameIn(List<String> values) {
            addCriterion("EASY_NAME in", values, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameNotIn(List<String> values) {
            addCriterion("EASY_NAME not in", values, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameBetween(String value1, String value2) {
            addCriterion("EASY_NAME between", value1, value2, "easyName");
            return (Criteria) this;
        }

        public Criteria andEasyNameNotBetween(String value1, String value2) {
            addCriterion("EASY_NAME not between", value1, value2, "easyName");
            return (Criteria) this;
        }

        public Criteria andFastCodeIsNull() {
            addCriterion("FAST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFastCodeIsNotNull() {
            addCriterion("FAST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFastCodeEqualTo(String value) {
            addCriterion("FAST_CODE =", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeNotEqualTo(String value) {
            addCriterion("FAST_CODE <>", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeGreaterThan(String value) {
            addCriterion("FAST_CODE >", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FAST_CODE >=", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeLessThan(String value) {
            addCriterion("FAST_CODE <", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeLessThanOrEqualTo(String value) {
            addCriterion("FAST_CODE <=", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeLike(String value) {
            addCriterion("FAST_CODE like", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeNotLike(String value) {
            addCriterion("FAST_CODE not like", value, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeIn(List<String> values) {
            addCriterion("FAST_CODE in", values, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeNotIn(List<String> values) {
            addCriterion("FAST_CODE not in", values, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeBetween(String value1, String value2) {
            addCriterion("FAST_CODE between", value1, value2, "fastCode");
            return (Criteria) this;
        }

        public Criteria andFastCodeNotBetween(String value1, String value2) {
            addCriterion("FAST_CODE not between", value1, value2, "fastCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNull() {
            addCriterion("POST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNotNull() {
            addCriterion("POST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostCodeEqualTo(String value) {
            addCriterion("POST_CODE =", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotEqualTo(String value) {
            addCriterion("POST_CODE <>", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThan(String value) {
            addCriterion("POST_CODE >", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("POST_CODE >=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThan(String value) {
            addCriterion("POST_CODE <", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThanOrEqualTo(String value) {
            addCriterion("POST_CODE <=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLike(String value) {
            addCriterion("POST_CODE like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotLike(String value) {
            addCriterion("POST_CODE not like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIn(List<String> values) {
            addCriterion("POST_CODE in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotIn(List<String> values) {
            addCriterion("POST_CODE not in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeBetween(String value1, String value2) {
            addCriterion("POST_CODE between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotBetween(String value1, String value2) {
            addCriterion("POST_CODE not between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andOrgAddressIsNull() {
            addCriterion("ORG_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andOrgAddressIsNotNull() {
            addCriterion("ORG_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAddressEqualTo(String value) {
            addCriterion("ORG_ADDRESS =", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressNotEqualTo(String value) {
            addCriterion("ORG_ADDRESS <>", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressGreaterThan(String value) {
            addCriterion("ORG_ADDRESS >", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_ADDRESS >=", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressLessThan(String value) {
            addCriterion("ORG_ADDRESS <", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressLessThanOrEqualTo(String value) {
            addCriterion("ORG_ADDRESS <=", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressLike(String value) {
            addCriterion("ORG_ADDRESS like", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressNotLike(String value) {
            addCriterion("ORG_ADDRESS not like", value, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressIn(List<String> values) {
            addCriterion("ORG_ADDRESS in", values, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressNotIn(List<String> values) {
            addCriterion("ORG_ADDRESS not in", values, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressBetween(String value1, String value2) {
            addCriterion("ORG_ADDRESS between", value1, value2, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgAddressNotBetween(String value1, String value2) {
            addCriterion("ORG_ADDRESS not between", value1, value2, "orgAddress");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeIsNull() {
            addCriterion("ORG_FAXE is null");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeIsNotNull() {
            addCriterion("ORG_FAXE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeEqualTo(String value) {
            addCriterion("ORG_FAXE =", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeNotEqualTo(String value) {
            addCriterion("ORG_FAXE <>", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeGreaterThan(String value) {
            addCriterion("ORG_FAXE >", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_FAXE >=", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeLessThan(String value) {
            addCriterion("ORG_FAXE <", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeLessThanOrEqualTo(String value) {
            addCriterion("ORG_FAXE <=", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeLike(String value) {
            addCriterion("ORG_FAXE like", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeNotLike(String value) {
            addCriterion("ORG_FAXE not like", value, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeIn(List<String> values) {
            addCriterion("ORG_FAXE in", values, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeNotIn(List<String> values) {
            addCriterion("ORG_FAXE not in", values, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeBetween(String value1, String value2) {
            addCriterion("ORG_FAXE between", value1, value2, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andOrgFaxeNotBetween(String value1, String value2) {
            addCriterion("ORG_FAXE not between", value1, value2, "orgFaxe");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNull() {
            addCriterion("TOWN_ID is null");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNotNull() {
            addCriterion("TOWN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTownIdEqualTo(BigDecimal value) {
            addCriterion("TOWN_ID =", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotEqualTo(BigDecimal value) {
            addCriterion("TOWN_ID <>", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThan(BigDecimal value) {
            addCriterion("TOWN_ID >", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOWN_ID >=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThan(BigDecimal value) {
            addCriterion("TOWN_ID <", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOWN_ID <=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdIn(List<BigDecimal> values) {
            addCriterion("TOWN_ID in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotIn(List<BigDecimal> values) {
            addCriterion("TOWN_ID not in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOWN_ID between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOWN_ID not between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("CITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("CITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(BigDecimal value) {
            addCriterion("CITY_ID =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(BigDecimal value) {
            addCriterion("CITY_ID <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(BigDecimal value) {
            addCriterion("CITY_ID >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CITY_ID >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(BigDecimal value) {
            addCriterion("CITY_ID <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CITY_ID <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<BigDecimal> values) {
            addCriterion("CITY_ID in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<BigDecimal> values) {
            addCriterion("CITY_ID not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CITY_ID between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CITY_ID not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andLinkPersonIsNull() {
            addCriterion("LINK_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andLinkPersonIsNotNull() {
            addCriterion("LINK_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andLinkPersonEqualTo(String value) {
            addCriterion("LINK_PERSON =", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonNotEqualTo(String value) {
            addCriterion("LINK_PERSON <>", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonGreaterThan(String value) {
            addCriterion("LINK_PERSON >", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonGreaterThanOrEqualTo(String value) {
            addCriterion("LINK_PERSON >=", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonLessThan(String value) {
            addCriterion("LINK_PERSON <", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonLessThanOrEqualTo(String value) {
            addCriterion("LINK_PERSON <=", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonLike(String value) {
            addCriterion("LINK_PERSON like", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonNotLike(String value) {
            addCriterion("LINK_PERSON not like", value, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonIn(List<String> values) {
            addCriterion("LINK_PERSON in", values, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonNotIn(List<String> values) {
            addCriterion("LINK_PERSON not in", values, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonBetween(String value1, String value2) {
            addCriterion("LINK_PERSON between", value1, value2, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPersonNotBetween(String value1, String value2) {
            addCriterion("LINK_PERSON not between", value1, value2, "linkPerson");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNull() {
            addCriterion("LINK_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNotNull() {
            addCriterion("LINK_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneEqualTo(String value) {
            addCriterion("LINK_PHONE =", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotEqualTo(String value) {
            addCriterion("LINK_PHONE <>", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThan(String value) {
            addCriterion("LINK_PHONE >", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("LINK_PHONE >=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThan(String value) {
            addCriterion("LINK_PHONE <", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThanOrEqualTo(String value) {
            addCriterion("LINK_PHONE <=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLike(String value) {
            addCriterion("LINK_PHONE like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotLike(String value) {
            addCriterion("LINK_PHONE not like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIn(List<String> values) {
            addCriterion("LINK_PHONE in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotIn(List<String> values) {
            addCriterion("LINK_PHONE not in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneBetween(String value1, String value2) {
            addCriterion("LINK_PHONE between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotBetween(String value1, String value2) {
            addCriterion("LINK_PHONE not between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andOrgDescIsNull() {
            addCriterion("ORG_DESC is null");
            return (Criteria) this;
        }

        public Criteria andOrgDescIsNotNull() {
            addCriterion("ORG_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andOrgDescEqualTo(String value) {
            addCriterion("ORG_DESC =", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescNotEqualTo(String value) {
            addCriterion("ORG_DESC <>", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescGreaterThan(String value) {
            addCriterion("ORG_DESC >", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_DESC >=", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescLessThan(String value) {
            addCriterion("ORG_DESC <", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescLessThanOrEqualTo(String value) {
            addCriterion("ORG_DESC <=", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescLike(String value) {
            addCriterion("ORG_DESC like", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescNotLike(String value) {
            addCriterion("ORG_DESC not like", value, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescIn(List<String> values) {
            addCriterion("ORG_DESC in", values, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescNotIn(List<String> values) {
            addCriterion("ORG_DESC not in", values, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescBetween(String value1, String value2) {
            addCriterion("ORG_DESC between", value1, value2, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andOrgDescNotBetween(String value1, String value2) {
            addCriterion("ORG_DESC not between", value1, value2, "orgDesc");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNull() {
            addCriterion("CREATE_USERID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNotNull() {
            addCriterion("CREATE_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridEqualTo(BigDecimal value) {
            addCriterion("CREATE_USERID =", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotEqualTo(BigDecimal value) {
            addCriterion("CREATE_USERID <>", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThan(BigDecimal value) {
            addCriterion("CREATE_USERID >", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_USERID >=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThan(BigDecimal value) {
            addCriterion("CREATE_USERID <", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_USERID <=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIn(List<BigDecimal> values) {
            addCriterion("CREATE_USERID in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotIn(List<BigDecimal> values) {
            addCriterion("CREATE_USERID not in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_USERID between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_USERID not between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidIsNull() {
            addCriterion("CREATE_ORGID is null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidIsNotNull() {
            addCriterion("CREATE_ORGID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidEqualTo(BigDecimal value) {
            addCriterion("CREATE_ORGID =", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidNotEqualTo(BigDecimal value) {
            addCriterion("CREATE_ORGID <>", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidGreaterThan(BigDecimal value) {
            addCriterion("CREATE_ORGID >", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_ORGID >=", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidLessThan(BigDecimal value) {
            addCriterion("CREATE_ORGID <", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_ORGID <=", value, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidIn(List<BigDecimal> values) {
            addCriterion("CREATE_ORGID in", values, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidNotIn(List<BigDecimal> values) {
            addCriterion("CREATE_ORGID not in", values, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_ORGID between", value1, value2, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateOrgidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_ORGID not between", value1, value2, "createOrgid");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyUseridIsNull() {
            addCriterion("MODIFY_USERID is null");
            return (Criteria) this;
        }

        public Criteria andModifyUseridIsNotNull() {
            addCriterion("MODIFY_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUseridEqualTo(BigDecimal value) {
            addCriterion("MODIFY_USERID =", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridNotEqualTo(BigDecimal value) {
            addCriterion("MODIFY_USERID <>", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridGreaterThan(BigDecimal value) {
            addCriterion("MODIFY_USERID >", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MODIFY_USERID >=", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridLessThan(BigDecimal value) {
            addCriterion("MODIFY_USERID <", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MODIFY_USERID <=", value, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridIn(List<BigDecimal> values) {
            addCriterion("MODIFY_USERID in", values, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridNotIn(List<BigDecimal> values) {
            addCriterion("MODIFY_USERID not in", values, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODIFY_USERID between", value1, value2, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyUseridNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODIFY_USERID not between", value1, value2, "modifyUserid");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andWubiCodeIsNull() {
            addCriterion("WUBI_CODE is null");
            return (Criteria) this;
        }

        public Criteria andWubiCodeIsNotNull() {
            addCriterion("WUBI_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andWubiCodeEqualTo(String value) {
            addCriterion("WUBI_CODE =", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeNotEqualTo(String value) {
            addCriterion("WUBI_CODE <>", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeGreaterThan(String value) {
            addCriterion("WUBI_CODE >", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeGreaterThanOrEqualTo(String value) {
            addCriterion("WUBI_CODE >=", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeLessThan(String value) {
            addCriterion("WUBI_CODE <", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeLessThanOrEqualTo(String value) {
            addCriterion("WUBI_CODE <=", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeLike(String value) {
            addCriterion("WUBI_CODE like", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeNotLike(String value) {
            addCriterion("WUBI_CODE not like", value, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeIn(List<String> values) {
            addCriterion("WUBI_CODE in", values, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeNotIn(List<String> values) {
            addCriterion("WUBI_CODE not in", values, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeBetween(String value1, String value2) {
            addCriterion("WUBI_CODE between", value1, value2, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andWubiCodeNotBetween(String value1, String value2) {
            addCriterion("WUBI_CODE not between", value1, value2, "wubiCode");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNull() {
            addCriterion("ENABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNotNull() {
            addCriterion("ENABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagEqualTo(String value) {
            addCriterion("ENABLE_FLAG =", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotEqualTo(String value) {
            addCriterion("ENABLE_FLAG <>", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThan(String value) {
            addCriterion("ENABLE_FLAG >", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ENABLE_FLAG >=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThan(String value) {
            addCriterion("ENABLE_FLAG <", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThanOrEqualTo(String value) {
            addCriterion("ENABLE_FLAG <=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLike(String value) {
            addCriterion("ENABLE_FLAG like", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotLike(String value) {
            addCriterion("ENABLE_FLAG not like", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIn(List<String> values) {
            addCriterion("ENABLE_FLAG in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotIn(List<String> values) {
            addCriterion("ENABLE_FLAG not in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagBetween(String value1, String value2) {
            addCriterion("ENABLE_FLAG between", value1, value2, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotBetween(String value1, String value2) {
            addCriterion("ENABLE_FLAG not between", value1, value2, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andPartIdIsNull() {
            addCriterion("PART_ID is null");
            return (Criteria) this;
        }

        public Criteria andPartIdIsNotNull() {
            addCriterion("PART_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPartIdEqualTo(BigDecimal value) {
            addCriterion("PART_ID =", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdNotEqualTo(BigDecimal value) {
            addCriterion("PART_ID <>", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdGreaterThan(BigDecimal value) {
            addCriterion("PART_ID >", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PART_ID >=", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdLessThan(BigDecimal value) {
            addCriterion("PART_ID <", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PART_ID <=", value, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdIn(List<BigDecimal> values) {
            addCriterion("PART_ID in", values, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdNotIn(List<BigDecimal> values) {
            addCriterion("PART_ID not in", values, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PART_ID between", value1, value2, "partId");
            return (Criteria) this;
        }

        public Criteria andPartIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PART_ID not between", value1, value2, "partId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WS_GOVERNMENT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}