package com.cym.struts2.demo1.bean;

import java.math.BigDecimal;
import java.util.Date;

public class WsGovernment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.REGION_ID
     *
     * @mbggenerated
     */
    private BigDecimal regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ORG_CODE
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ORG_NAME
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.EASY_NAME
     *
     * @mbggenerated
     */
    private String easyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.FAST_CODE
     *
     * @mbggenerated
     */
    private String fastCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.POST_CODE
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ORG_ADDRESS
     *
     * @mbggenerated
     */
    private String orgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ORG_FAXE
     *
     * @mbggenerated
     */
    private String orgFaxe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.TOWN_ID
     *
     * @mbggenerated
     */
    private BigDecimal townId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.CITY_ID
     *
     * @mbggenerated
     */
    private BigDecimal cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.LINK_PERSON
     *
     * @mbggenerated
     */
    private String linkPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.LINK_PHONE
     *
     * @mbggenerated
     */
    private String linkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ORG_DESC
     *
     * @mbggenerated
     */
    private String orgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.CREATE_USERID
     *
     * @mbggenerated
     */
    private BigDecimal createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.CREATE_ORGID
     *
     * @mbggenerated
     */
    private BigDecimal createOrgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.MODIFY_USERID
     *
     * @mbggenerated
     */
    private BigDecimal modifyUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.WUBI_CODE
     *
     * @mbggenerated
     */
    private String wubiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.ENABLE_FLAG
     *
     * @mbggenerated
     */
    private String enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WS_GOVERNMENT.PART_ID
     *
     * @mbggenerated
     */
    private BigDecimal partId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ID
     *
     * @return the value of WS_GOVERNMENT.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ID
     *
     * @param id the value for WS_GOVERNMENT.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.REGION_ID
     *
     * @return the value of WS_GOVERNMENT.REGION_ID
     *
     * @mbggenerated
     */
    public BigDecimal getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.REGION_ID
     *
     * @param regionId the value for WS_GOVERNMENT.REGION_ID
     *
     * @mbggenerated
     */
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ORG_CODE
     *
     * @return the value of WS_GOVERNMENT.ORG_CODE
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ORG_CODE
     *
     * @param orgCode the value for WS_GOVERNMENT.ORG_CODE
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ORG_NAME
     *
     * @return the value of WS_GOVERNMENT.ORG_NAME
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ORG_NAME
     *
     * @param orgName the value for WS_GOVERNMENT.ORG_NAME
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.EASY_NAME
     *
     * @return the value of WS_GOVERNMENT.EASY_NAME
     *
     * @mbggenerated
     */
    public String getEasyName() {
        return easyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.EASY_NAME
     *
     * @param easyName the value for WS_GOVERNMENT.EASY_NAME
     *
     * @mbggenerated
     */
    public void setEasyName(String easyName) {
        this.easyName = easyName == null ? null : easyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.FAST_CODE
     *
     * @return the value of WS_GOVERNMENT.FAST_CODE
     *
     * @mbggenerated
     */
    public String getFastCode() {
        return fastCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.FAST_CODE
     *
     * @param fastCode the value for WS_GOVERNMENT.FAST_CODE
     *
     * @mbggenerated
     */
    public void setFastCode(String fastCode) {
        this.fastCode = fastCode == null ? null : fastCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.POST_CODE
     *
     * @return the value of WS_GOVERNMENT.POST_CODE
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.POST_CODE
     *
     * @param postCode the value for WS_GOVERNMENT.POST_CODE
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ORG_ADDRESS
     *
     * @return the value of WS_GOVERNMENT.ORG_ADDRESS
     *
     * @mbggenerated
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ORG_ADDRESS
     *
     * @param orgAddress the value for WS_GOVERNMENT.ORG_ADDRESS
     *
     * @mbggenerated
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ORG_FAXE
     *
     * @return the value of WS_GOVERNMENT.ORG_FAXE
     *
     * @mbggenerated
     */
    public String getOrgFaxe() {
        return orgFaxe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ORG_FAXE
     *
     * @param orgFaxe the value for WS_GOVERNMENT.ORG_FAXE
     *
     * @mbggenerated
     */
    public void setOrgFaxe(String orgFaxe) {
        this.orgFaxe = orgFaxe == null ? null : orgFaxe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.TOWN_ID
     *
     * @return the value of WS_GOVERNMENT.TOWN_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTownId() {
        return townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.TOWN_ID
     *
     * @param townId the value for WS_GOVERNMENT.TOWN_ID
     *
     * @mbggenerated
     */
    public void setTownId(BigDecimal townId) {
        this.townId = townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.CITY_ID
     *
     * @return the value of WS_GOVERNMENT.CITY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.CITY_ID
     *
     * @param cityId the value for WS_GOVERNMENT.CITY_ID
     *
     * @mbggenerated
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.LINK_PERSON
     *
     * @return the value of WS_GOVERNMENT.LINK_PERSON
     *
     * @mbggenerated
     */
    public String getLinkPerson() {
        return linkPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.LINK_PERSON
     *
     * @param linkPerson the value for WS_GOVERNMENT.LINK_PERSON
     *
     * @mbggenerated
     */
    public void setLinkPerson(String linkPerson) {
        this.linkPerson = linkPerson == null ? null : linkPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.LINK_PHONE
     *
     * @return the value of WS_GOVERNMENT.LINK_PHONE
     *
     * @mbggenerated
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.LINK_PHONE
     *
     * @param linkPhone the value for WS_GOVERNMENT.LINK_PHONE
     *
     * @mbggenerated
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.EMAIL
     *
     * @return the value of WS_GOVERNMENT.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.EMAIL
     *
     * @param email the value for WS_GOVERNMENT.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ORG_DESC
     *
     * @return the value of WS_GOVERNMENT.ORG_DESC
     *
     * @mbggenerated
     */
    public String getOrgDesc() {
        return orgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ORG_DESC
     *
     * @param orgDesc the value for WS_GOVERNMENT.ORG_DESC
     *
     * @mbggenerated
     */
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc == null ? null : orgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.CREATE_USERID
     *
     * @return the value of WS_GOVERNMENT.CREATE_USERID
     *
     * @mbggenerated
     */
    public BigDecimal getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.CREATE_USERID
     *
     * @param createUserid the value for WS_GOVERNMENT.CREATE_USERID
     *
     * @mbggenerated
     */
    public void setCreateUserid(BigDecimal createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.CREATE_ORGID
     *
     * @return the value of WS_GOVERNMENT.CREATE_ORGID
     *
     * @mbggenerated
     */
    public BigDecimal getCreateOrgid() {
        return createOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.CREATE_ORGID
     *
     * @param createOrgid the value for WS_GOVERNMENT.CREATE_ORGID
     *
     * @mbggenerated
     */
    public void setCreateOrgid(BigDecimal createOrgid) {
        this.createOrgid = createOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.CREATE_DATE
     *
     * @return the value of WS_GOVERNMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.CREATE_DATE
     *
     * @param createDate the value for WS_GOVERNMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.MODIFY_USERID
     *
     * @return the value of WS_GOVERNMENT.MODIFY_USERID
     *
     * @mbggenerated
     */
    public BigDecimal getModifyUserid() {
        return modifyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.MODIFY_USERID
     *
     * @param modifyUserid the value for WS_GOVERNMENT.MODIFY_USERID
     *
     * @mbggenerated
     */
    public void setModifyUserid(BigDecimal modifyUserid) {
        this.modifyUserid = modifyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.MODIFY_DATE
     *
     * @return the value of WS_GOVERNMENT.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.MODIFY_DATE
     *
     * @param modifyDate the value for WS_GOVERNMENT.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.WUBI_CODE
     *
     * @return the value of WS_GOVERNMENT.WUBI_CODE
     *
     * @mbggenerated
     */
    public String getWubiCode() {
        return wubiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.WUBI_CODE
     *
     * @param wubiCode the value for WS_GOVERNMENT.WUBI_CODE
     *
     * @mbggenerated
     */
    public void setWubiCode(String wubiCode) {
        this.wubiCode = wubiCode == null ? null : wubiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.ENABLE_FLAG
     *
     * @return the value of WS_GOVERNMENT.ENABLE_FLAG
     *
     * @mbggenerated
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.ENABLE_FLAG
     *
     * @param enableFlag the value for WS_GOVERNMENT.ENABLE_FLAG
     *
     * @mbggenerated
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag == null ? null : enableFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WS_GOVERNMENT.PART_ID
     *
     * @return the value of WS_GOVERNMENT.PART_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WS_GOVERNMENT.PART_ID
     *
     * @param partId the value for WS_GOVERNMENT.PART_ID
     *
     * @mbggenerated
     */
    public void setPartId(BigDecimal partId) {
        this.partId = partId;
    }

    @Override
    public String toString() {
        return "WsGovernment{" +
                "id=" + id +
                ", regionId=" + regionId +
                ", orgCode='" + orgCode + '\'' +
                ", orgName='" + orgName + '\'' +
                ", easyName='" + easyName + '\'' +
                ", fastCode='" + fastCode + '\'' +
                ", postCode='" + postCode + '\'' +
                ", orgAddress='" + orgAddress + '\'' +
                ", orgFaxe='" + orgFaxe + '\'' +
                ", townId=" + townId +
                ", cityId=" + cityId +
                ", linkPerson='" + linkPerson + '\'' +
                ", linkPhone='" + linkPhone + '\'' +
                ", email='" + email + '\'' +
                ", orgDesc='" + orgDesc + '\'' +
                ", createUserid=" + createUserid +
                ", createOrgid=" + createOrgid +
                ", createDate=" + createDate +
                ", modifyUserid=" + modifyUserid +
                ", modifyDate=" + modifyDate +
                ", wubiCode='" + wubiCode + '\'' +
                ", enableFlag='" + enableFlag + '\'' +
                ", partId=" + partId +
                '}';
    }
}